spring.application.name=volleyflow

spring.datasource.url = jdbc:postgresql://localhost:5432/volleyflow
spring.datasource.username = admin
spring.datasource.password = admin
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=3W3Pb3x0dW8tM3V0S1Qtc2VjcmV0LWtleS12b2xsZXlmbG93LTIwMjYtand0LXNpZ24=
app.jwt.expiration-ms=3600000
spring.jpa.open-in-view=false
