spring.application.name=volleyflow

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/volleyflow}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
app.jwt.secret=${JWT_SECRET:ZGVtby1qd3Qtc2VjcmV0LWZvci1sb2NhbC1kZXYtb25seS1wbGFjZWhvbGRlci0zMi1ieXRlcw==}
app.jwt.expiration-ms=3600000
spring.jpa.open-in-view=false
