create table volleyball_match_set_statistic (
    id bigserial primary key,
    external_id uuid not null unique,
    set_id bigint not null references volleyball_match_set(id) on delete cascade,
    club_id bigint not null references club(id),
    player_profile_id bigint not null references person_profile(id),
    points integer not null,
    balance integer not null,
    serve_total integer not null,
    serve_error integer not null,
    serve_aces integer not null,
    reception_total integer not null,
    reception_error integer not null,
    reception_positive_percent integer not null,
    reception_perfect_percent integer not null,
    attack_total integer not null,
    attack_error integer not null,
    attack_blocked integer not null,
    attack_points integer not null,
    block_points integer not null,
    block_touches integer not null,
    defense integer not null,
    assists integer not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone,
    version integer not null default 0,
    constraint uk_match_set_statistic_set_club_player unique (set_id, club_id, player_profile_id)
);
